// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
 
using NUnit.Framework;
[TestFixture]
public class SpbSpbTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
         driver.Quit();
        Console.WriteLine("Тест");
    }
    [Test]
    public void spbSpb()
    {
        driver.Navigate().GoToUrl("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true");
        driver.FindElement(By.Id("login-button")).Click();
        driver.FindElement(By.Id("login-otp-button")).Click();
        System.Threading.Thread.Sleep(9000);
        //  Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Technical error"));
       // driver.FindElement(By.CssSelector("#OK")).Click();
        // Assert.AreEqual("Find me", by.FindElement(driver).Text);
       // System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#accounts-index > .underline")).Click();
        System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#payments-form > .underline")).Click();
        System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#cards-overview-index > .underline")).Click();
        System.Threading.Thread.Sleep(9000);
        //    driver.Close();
         driver.Navigate().GoToUrl("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true");
        //  driver.Navigate().GoToUrl("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=trueid=login-button");
        //  driver.FindElement(By.Id("login-otp-button")).Click();
      //  Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Technical error"));
        System.Threading.Thread.Sleep(9000);
      //  driver.FindElement(By.CssSelector("#accounts-index > .underline")).Click();
      //  System.Threading.Thread.Sleep(9000);
      //  driver.FindElement(By.CssSelector("#payments-form > .underline")).Click();
      //  System.Threading.Thread.Sleep(9000);
      //  driver.FindElement(By.CssSelector("#cards-overview-index > .underline")).Click();
     //   System.Threading.Thread.Sleep(9000);
      //  driver.Close();
        driver.FindElement(By.Id("login-button")).Click();
        driver.FindElement(By.Id("login-otp-button")).Click();
        System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#accounts-index > .underline")).Click();
        System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#payments-form > .underline")).Click();
        System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#cards-overview-index > .underline")).Click();
        System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#deposits-index > .underline")).Click();
        System.Threading.Thread.Sleep(9000);
       // driver.Close();
       driver.Navigate().GoToUrl("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true");
        driver.FindElement(By.Id("login-button")).Click();
       
        driver.FindElement(By.Id("login-otp-button")).Click();
        System.Threading.Thread.Sleep(9000);
        driver.FindElement(By.CssSelector("#accounts-index > .underline")).Click();
        driver.FindElement(By.Id("payments-form")).Click();
        driver.FindElement(By.CssSelector("#cards-overview-index > .underline")).Click();
         driver.Close();
         Console.WriteLine("Тест");
        Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Technical error"));
    }
}
